
set_pin_physical_constraints -pin_name {SPI_NARST} -offset 6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CONFIG} -offset 6.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PLL_EN} -offset 7.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DIGRST} -offset 7.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_AFC_EN} -offset 8.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FAFC_EN} -offset 9 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CTRL} -offset 9.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PHESIG_GEN_EN} -offset 10.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DTC_GAINCAL_EN} -offset 10.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DTC_EN} -offset 11.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_EN} -offset 12 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DSM_EN} -offset 12.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PDS_EN} -offset 13.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_EN} -offset 13.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_SPD_EN} -offset 14.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PFD_EN} -offset 15 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP_EN} -offset 15.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PRECHARGE_EN} -offset 16.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[12]} -offset 16.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[11]} -offset 17.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[10]} -offset 18 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[9]} -offset 18.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[8]} -offset 19.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[7]} -offset 19.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[6]} -offset 20.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[5]} -offset 21 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[4]} -offset 21.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[3]} -offset 22.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[2]} -offset 22.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[1]} -offset 23.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[0]} -offset 24 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[12]} -offset 24.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[11]} -offset 25.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[10]} -offset 25.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[9]} -offset 26.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[8]} -offset 27 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[7]} -offset 27.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[6]} -offset 28.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[5]} -offset 28.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[4]} -offset 29.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[3]} -offset 30 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[2]} -offset 30.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[1]} -offset 31.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[0]} -offset 31.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[12]} -offset 32.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[11]} -offset 33 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[10]} -offset 33.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[9]} -offset 34.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[8]} -offset 34.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[7]} -offset 35.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[6]} -offset 36 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[5]} -offset 36.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[4]} -offset 37.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[3]} -offset 37.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[2]} -offset 38.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[1]} -offset 39 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[0]} -offset 39.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[4]} -offset 40.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[3]} -offset 40.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[2]} -offset 41.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[1]} -offset 42 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[0]} -offset 42.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KB[4]} -offset 43.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KB[3]} -offset 43.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KB[2]} -offset 44.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KB[1]} -offset 45 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KB[0]} -offset 45.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KC[4]} -offset 46.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KC[3]} -offset 46.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KC[2]} -offset 47.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KC[1]} -offset 48 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KC[0]} -offset 48.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[3]} -offset 49.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[2]} -offset 49.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[1]} -offset 50.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[0]} -offset 51 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[4]} -offset 51.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[3]} -offset 52.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[2]} -offset 52.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[1]} -offset 53.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[0]} -offset 54 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CALIORDER[2]} -offset 54.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CALIORDER[1]} -offset 55.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CALIORDER[0]} -offset 55.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PSEC[2]} -offset 56.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PSEC[1]} -offset 57 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PSEC[0]} -offset 57.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_SECSEL_TEST[1]} -offset 58.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_SECSEL_TEST[0]} -offset 58.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[3]} -offset 59.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[2]} -offset 60 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[1]} -offset 60.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[0]} -offset 61.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CAL_MODE} -offset 61.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[8]} -offset 62.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[7]} -offset 63 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[6]} -offset 63.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[5]} -offset 64.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[4]} -offset 64.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[3]} -offset 65.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[2]} -offset 66 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[1]} -offset 66.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[0]} -offset 67.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[8]} -offset 67.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[7]} -offset 68.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[6]} -offset 69 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[5]} -offset 69.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[4]} -offset 70.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[3]} -offset 70.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[2]} -offset 71.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[1]} -offset 72 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[0]} -offset 72.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSOURCE} -offset 73.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL[2]} -offset 73.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL[1]} -offset 74.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL[0]} -offset 75 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_SNPCNTTDC_EN} -offset 75.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CNTPREDIV_EN} -offset 76.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[6]} -offset 76.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[5]} -offset 77.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[4]} -offset 78 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[3]} -offset 78.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[2]} -offset 79.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[1]} -offset 79.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[0]} -offset 80.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[8]} -offset 81 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[7]} -offset 81.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[6]} -offset 82.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[5]} -offset 82.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[4]} -offset 83.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[3]} -offset 84 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[2]} -offset 84.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[1]} -offset 85.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[0]} -offset 85.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_S[2]} -offset 86.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_S[1]} -offset 87 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_S[0]} -offset 87.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PHASECAL_EN} -offset 88.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_DIV[2]} -offset 88.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_DIV[1]} -offset 89.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_DIV[0]} -offset 90 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[4]} -offset 90.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[3]} -offset 91.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[2]} -offset 91.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[1]} -offset 92.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[0]} -offset 93 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[4]} -offset 93.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[3]} -offset 94.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[2]} -offset 94.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[1]} -offset 95.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[0]} -offset 96 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_DN_EN} -offset 96.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[12]} -offset 97.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[11]} -offset 97.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[10]} -offset 98.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[9]} -offset 99 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[8]} -offset 99.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[7]} -offset 100.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[6]} -offset 100.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[5]} -offset 101.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[4]} -offset 102 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[3]} -offset 102.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[2]} -offset 103.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[1]} -offset 103.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[0]} -offset 104.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {FLOCK} -offset 105 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {LO_PCALI_DONE} -offset 105.6 -layers {M3} -width 0.08 -depth 0 -side 3
