set_pin_physical_constraints -pin_name {SPI_FAFC_EN} -offset 6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_NARST} -offset 6.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {REF} -offset 7.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {CNT7BIT[6]} -offset 20 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {CNT7BIT[5]} -offset 20.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {CNT7BIT[4]} -offset 21.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {CNT7BIT[3]} -offset 21.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {CNT7BIT[2]} -offset 22.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {CNT7BIT[1]} -offset 23 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {CNT7BIT[0]} -offset 23.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {TDCCODE[5]} -offset 24.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {TDCCODE[4]} -offset 24.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {TDCCODE[3]} -offset 25.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {TDCCODE[2]} -offset 26 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {TDCCODE[1]} -offset 26.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {TDCCODE[0]} -offset 27.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {MMDNRST_FAFC} -offset 7.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {QN1S[7]} -offset 27.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QN1S[6]} -offset 28.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QN1S[5]} -offset 29 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QN1S[4]} -offset 29.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QN1S[3]} -offset 30.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QN1S[2]} -offset 30.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QN2S[7]} -offset 31.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QN2S[6]} -offset 32 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QN2S[5]} -offset 32.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QN2S[4]} -offset 33.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QN2S[3]} -offset 33.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QN2S[2]} -offset 34.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP1S[7]} -offset 35 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP1S[6]} -offset 35.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP1S[5]} -offset 36.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP1S[4]} -offset 36.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP1S[3]} -offset 37.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP1S[2]} -offset 38 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP2S[7]} -offset 38.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP2S[6]} -offset 39.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP2S[5]} -offset 39.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP2S[4]} -offset 40.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP2S[3]} -offset 41 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {QP2S[2]} -offset 41.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {NRST2} -offset 42.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {FAFC_CTRL} -offset 6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FREQLOCK2} -offset 6.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWP[8]} -offset 7.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWP[7]} -offset 7.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWP[6]} -offset 8.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWP[5]} -offset 9 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWP[4]} -offset 9.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWP[3]} -offset 10.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWP[2]} -offset 10.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWP[1]} -offset 11.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWP[0]} -offset 12 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWN[8]} -offset 12.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWN[7]} -offset 13.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWN[6]} -offset 13.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWN[5]} -offset 14.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWN[4]} -offset 15 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWN[3]} -offset 15.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWN[2]} -offset 16.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWN[1]} -offset 16.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FAFC_OTWN[0]} -offset 17.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[24]} -offset 18 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[23]} -offset 18.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[22]} -offset 19.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[21]} -offset 19.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[20]} -offset 20.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[19]} -offset 21 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[18]} -offset 21.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[17]} -offset 22.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[16]} -offset 22.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[15]} -offset 23.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[14]} -offset 24 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[13]} -offset 24.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[12]} -offset 25.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[11]} -offset 25.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[10]} -offset 26.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[9]} -offset 27 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[8]} -offset 27.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[7]} -offset 28.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[6]} -offset 28.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[5]} -offset 29.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[4]} -offset 30 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[3]} -offset 30.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[2]} -offset 31.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[1]} -offset 31.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[0]} -offset 32.4 -layers {M4} -width 0.08 -depth 0 -side 4

set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI_O[4]} -offset 39 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI_O[3]} -offset 39.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI_O[2]} -offset 40.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI_O[1]} -offset 40.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI_O[0]} -offset 41.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[15]} -offset 42 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[14]} -offset 42.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[13]} -offset 43.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[12]} -offset 43.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[11]} -offset 44.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[10]} -offset 45 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[9]} -offset 45.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[8]} -offset 46.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[7]} -offset 46.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[6]} -offset 47.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[5]} -offset 48 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[4]} -offset 48.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[3]} -offset 49.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[2]} -offset 49.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[1]} -offset 50.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[0]} -offset 51 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_AUXMMD_SEL_O} -offset 51.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[7]} -offset 52.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[6]} -offset 52.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[5]} -offset 53.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[4]} -offset 54 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[3]} -offset 54.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[2]} -offset 55.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[1]} -offset 55.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[0]} -offset 56.4 -layers {M4} -width 0.08 -depth 0 -side 4
