set_pin_physical_constraints -pin_name {SPI_FCW[0]} -offset 6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW[1]} -offset 6.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW[2]} -offset 7.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW[3]} -offset 7.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW[4]} -offset 8.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW[5]} -offset 9 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW[6]} -offset 9.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW[7]} -offset 10.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW[8]} -offset 10.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW[9]} -offset 11.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW[10]} -offset 12 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CONFIG} -offset 12.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP_EN} -offset 84 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PFD_EN} -offset 84.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_SPD_EN} -offset 85.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_EN} -offset 85.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DSM_EN} -offset 86.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_EN} -offset 87 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DTC_EN} -offset 87.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DTC_GAINCAL_EN} -offset 88.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PHESIG_GEN_EN} -offset 88.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PLL_EN} -offset 89.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CTRL} -offset 90 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_NARST} -offset 91.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_SYS_EDGE_SEL[0]} -offset 94.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_SYS_EDGE_SEL[1]} -offset 95.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_SYS_EDGE_SEL[2]} -offset 96 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DSM_BOOTMODE} -offset 96.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PHASECAL_EN_SEL} -offset 97.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PRECHARGE_EN} -offset 113.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[0]} -offset 124.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[1]} -offset 125.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[2]} -offset 126 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[3]} -offset 126.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[4]} -offset 127.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[0]} -offset 132 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[1]} -offset 132.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[2]} -offset 133.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[3]} -offset 133.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[0]} -offset 139.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[1]} -offset 139.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[2]} -offset 140.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[3]} -offset 141 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[4]} -offset 141.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[7]} -offset 146.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[8]} -offset 147 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_S[0]} -offset 147.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_S[1]} -offset 148.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[0]} -offset 148.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[1]} -offset 149.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[2]} -offset 150 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[3]} -offset 150.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[4]} -offset 151.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[5]} -offset 151.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[6]} -offset 152.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[7]} -offset 153 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[8]} -offset 153.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[9]} -offset 154.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[10]} -offset 154.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[11]} -offset 155.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTC_INIT[12]} -offset 156 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[0]} -offset 164.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[1]} -offset 165 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[2]} -offset 165.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[3]} -offset 166.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[4]} -offset 166.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[5]} -offset 167.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[6]} -offset 168 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL[0]} -offset 168.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL[1]} -offset 169.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL[2]} -offset 169.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSOURCE} -offset 170.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[0]} -offset 171 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[1]} -offset 171.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[2]} -offset 172.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[3]} -offset 172.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[4]} -offset 173.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[5]} -offset 174 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[6]} -offset 174.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[7]} -offset 175.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[0]} -offset 175.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[1]} -offset 176.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[2]} -offset 177 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[3]} -offset 177.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[4]} -offset 178.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[5]} -offset 178.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[6]} -offset 179.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[7]} -offset 180 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[0]} -offset 183.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[1]} -offset 184.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[2]} -offset 184.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[3]} -offset 185.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[4]} -offset 186 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[5]} -offset 186.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[6]} -offset 187.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_DIV5} -offset 187.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_DIV[0]} -offset 188.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_DIV[1]} -offset 189 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_DIV[2]} -offset 189.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_DN_EN} -offset 190.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[0]} -offset 190.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[1]} -offset 191.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[2]} -offset 192 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[3]} -offset 192.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[4]} -offset 193.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[0]} -offset 193.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[1]} -offset 194.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[2]} -offset 195 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[3]} -offset 195.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[4]} -offset 196.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PHASECAL_EN} -offset 196.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_S[2]} -offset 208.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[8]} -offset 208.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[8]} -offset 209.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CAL_MODE} -offset 210 -layers {M3} -width 0.08 -depth 0 -side 3


set_pin_physical_constraints -pin_name {LO_STATE[1]} -offset 219.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {LO_STATE[0]} -offset 220 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SYNC_EN} -offset 220.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[34]} -offset 221.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[33]} -offset 221.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[32]} -offset 222.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[31]} -offset 223 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[30]} -offset 223.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[29]} -offset 224.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[28]} -offset 224.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[27]} -offset 225.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[26]} -offset 226 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[25]} -offset 226.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[24]} -offset 227.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[23]} -offset 227.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[22]} -offset 228.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[21]} -offset 229 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[20]} -offset 229.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[19]} -offset 230.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[18]} -offset 230.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[17]} -offset 231.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[16]} -offset 232 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[15]} -offset 232.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[14]} -offset 233.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[13]} -offset 233.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[12]} -offset 234.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[11]} -offset 235 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {LO_PCALI_DONE} -offset 235.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[0]} -offset 236.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[1]} -offset 236.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[2]} -offset 237.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[3]} -offset 238 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[4]} -offset 238.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[5]} -offset 239.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[6]} -offset 239.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[7]} -offset 240.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[8]} -offset 241 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[9]} -offset 241.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[10]} -offset 242.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[11]} -offset 242.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {KDTC_INT[12]} -offset 243.4 -layers {M4} -width 0.08 -depth 0 -side 4


set_pin_physical_constraints -pin_name {O_PRECHARGE_EN} -offset 6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTWSEL_O[2]} -offset 47.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTWSEL_O[1]} -offset 48 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTWSEL_O[0]} -offset 48.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_PHESIG_GEN_EN} -offset 49.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_DTC_GAINCAL_EN} -offset 49.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_DN_EN} -offset 50.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_DTC_EN} -offset 51 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_EN} -offset 51.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_DSM_EN} -offset 52.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_PFD_EN} -offset 53.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP_EN} -offset 54 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_SPD_EN} -offset 54.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP[8]} -offset 100 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP[7]} -offset 100.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP[6]} -offset 101.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP[5]} -offset 101.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP[4]} -offset 102.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP[3]} -offset 103 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP[2]} -offset 103.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP[1]} -offset 104.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP[0]} -offset 104.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP_N[8]} -offset 105.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP_N[7]} -offset 106 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP_N[6]} -offset 106.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP_N[5]} -offset 107.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP_N[4]} -offset 107.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP_N[3]} -offset 108.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP_N[2]} -offset 109 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP_N[1]} -offset 109.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CP_N[0]} -offset 110.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS[8]} -offset 110.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS[7]} -offset 111.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS[6]} -offset 112 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS[5]} -offset 112.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS[4]} -offset 113.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS[3]} -offset 113.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS[2]} -offset 114.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS[1]} -offset 115 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS[0]} -offset 115.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS_N[8]} -offset 116.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS_N[7]} -offset 116.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS_N[6]} -offset 117.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS_N[5]} -offset 118 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS_N[4]} -offset 118.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS_N[3]} -offset 119.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS_N[2]} -offset 119.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS_N[1]} -offset 120.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_CS_N[0]} -offset 121 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SYNC_REF} -offset 131 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[0]} -offset 140 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[1]} -offset 140.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[2]} -offset 141.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[3]} -offset 141.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[4]} -offset 142.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[5]} -offset 143 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[6]} -offset 143.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[7]} -offset 144.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[8]} -offset 144.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[9]} -offset 145.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[10]} -offset 146 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DCW_DELAY[11]} -offset 146.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_S[0]} -offset 147.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_S[1]} -offset 147.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_S[2]} -offset 148.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_P[8]} -offset 149 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_P[7]} -offset 149.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_P[6]} -offset 150.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_P[5]} -offset 150.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_P[4]} -offset 151.4 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_P[3]} -offset 152 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_P[2]} -offset 152.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_P[1]} -offset 153.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {O_MMD_P[0]} -offset 153.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {CKVD} -offset 170 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_SIG2} -offset 180 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_SIG} -offset 220 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {VDACCTRL_OUTP[1]} -offset 220.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {VDACCTRL_OUTP[0]} -offset 221.2 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {VDACCTRL_OUTN[1]} -offset 221.8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {VDACCTRL_OUTN[0]} -offset 222.4 -layers {M3} -width 0.08 -depth 0 -side 1


set_pin_physical_constraints -pin_name {AFC_OTWP[8]} -offset 6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWP[7]} -offset 6.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWP[6]} -offset 7.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWP[5]} -offset 7.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWP[4]} -offset 8.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWP[3]} -offset 9 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWP[2]} -offset 9.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWP[1]} -offset 10.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWP[0]} -offset 10.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWN[8]} -offset 11.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWN[7]} -offset 12 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWN[6]} -offset 12.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWN[5]} -offset 13.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWN[4]} -offset 13.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWN[3]} -offset 14.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWN[2]} -offset 15 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWN[1]} -offset 15.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_OTWN[0]} -offset 16.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {AFC_CTRL} -offset 16.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FREQLOCK} -offset 17.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[34]} -offset 18 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[33]} -offset 18.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[32]} -offset 19.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[31]} -offset 19.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[30]} -offset 20.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[29]} -offset 21 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[28]} -offset 21.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[27]} -offset 22.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[26]} -offset 22.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[25]} -offset 23.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[24]} -offset 24 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[23]} -offset 24.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[22]} -offset 25.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[21]} -offset 25.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[20]} -offset 26.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[19]} -offset 27 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[18]} -offset 27.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[17]} -offset 28.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[16]} -offset 28.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[15]} -offset 29.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[14]} -offset 30 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[13]} -offset 30.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[12]} -offset 31.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[11]} -offset 31.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[10]} -offset 32.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[9]} -offset 33 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[8]} -offset 33.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[7]} -offset 34.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[6]} -offset 34.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[5]} -offset 35.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[4]} -offset 36 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[3]} -offset 36.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[2]} -offset 37.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[1]} -offset 37.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[0]} -offset 38.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[8]} -offset 39 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[7]} -offset 39.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[6]} -offset 40.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[5]} -offset 40.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[4]} -offset 41.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[3]} -offset 42 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[2]} -offset 42.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[1]} -offset 43.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[0]} -offset 43.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_S_O[2]} -offset 44.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_S_O[1]} -offset 45 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_MMD_S_O[0]} -offset 45.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[6]} -offset 46.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[5]} -offset 46.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[4]} -offset 47.4 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[3]} -offset 48 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[2]} -offset 48.6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[1]} -offset 49.2 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[0]} -offset 49.8 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FLOCK} -offset 240 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LO_PHASECAL_EN_LO} -offset 241 -layers {M4} -width 0.08 -depth 0 -side 2
