set_pin_physical_constraints -pin_name {SPI_AFC_EN} -offset 6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_NARST} -offset 6.6 -layers {M3} -width 0.08 -depth 0 -side 3


set_pin_physical_constraints -pin_name {REF} -offset 6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {CKVD} -offset 6.6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWP[8]} -offset 6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWP[7]} -offset 6.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWP[6]} -offset 7.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWP[5]} -offset 7.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWP[4]} -offset 8.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWP[3]} -offset 9 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWP[2]} -offset 9.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWP[1]} -offset 10.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWP[0]} -offset 10.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWN[8]} -offset 11.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWN[7]} -offset 12 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWN[6]} -offset 12.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWN[5]} -offset 13.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWN[4]} -offset 13.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWN[3]} -offset 14.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWN[2]} -offset 15 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWN[1]} -offset 15.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_OTWN[0]} -offset 16.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {AFC_CTRL} -offset 16.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {FREQLOCK} -offset 17.4 -layers {M4} -width 0.08 -depth 0 -side 4

set_pin_physical_constraints -pin_name {SPI_FCW_O[16]} -offset 28.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[15]} -offset 29.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[14]} -offset 30 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[13]} -offset 30.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[12]} -offset 31.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[11]} -offset 31.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[10]} -offset 32.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[9]} -offset 33 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[8]} -offset 33.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[7]} -offset 34.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[6]} -offset 34.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[5]} -offset 35.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[4]} -offset 36 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[3]} -offset 36.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[2]} -offset 37.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[1]} -offset 37.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_O[0]} -offset 38.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[8]} -offset 39 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[7]} -offset 39.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[6]} -offset 40.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[5]} -offset 40.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[4]} -offset 41.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[3]} -offset 42 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[2]} -offset 42.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[1]} -offset 43.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[0]} -offset 43.8 -layers {M4} -width 0.08 -depth 0 -side 4

set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[6]} -offset 46.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[5]} -offset 46.8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[4]} -offset 47.4 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[3]} -offset 48 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[2]} -offset 48.6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[1]} -offset 49.2 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[0]} -offset 49.8 -layers {M4} -width 0.08 -depth 0 -side 4
