#up
set_pin_physical_constraints	-pin_name	{SPI_AFC_EN}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	6		
set_pin_physical_constraints	-pin_name	{SPI_NARST}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	6.6		
#down                                                                                                                     
set_pin_physical_constraints	-pin_name	{AFC_CTRL}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	6		
set_pin_physical_constraints	-pin_name	{FREQLOCK}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	6.6		
set_pin_physical_constraints	-pin_name	{AFC_OTWP[8]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	7.2		
set_pin_physical_constraints	-pin_name	{AFC_OTWP[7]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	7.8		
set_pin_physical_constraints	-pin_name	{AFC_OTWP[6]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	8.4		
set_pin_physical_constraints	-pin_name	{AFC_OTWP[5]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	9		
set_pin_physical_constraints	-pin_name	{AFC_OTWP[4]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	9.6		
set_pin_physical_constraints	-pin_name	{AFC_OTWP[3]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	10.2	
set_pin_physical_constraints	-pin_name	{AFC_OTWP[2]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	10.8	
set_pin_physical_constraints	-pin_name	{AFC_OTWP[1]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	11.4	
set_pin_physical_constraints	-pin_name	{AFC_OTWP[0]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	12		
set_pin_physical_constraints	-pin_name	{AFC_OTWN[8]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	12.6	
set_pin_physical_constraints	-pin_name	{AFC_OTWN[7]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	13.2	
set_pin_physical_constraints	-pin_name	{AFC_OTWN[6]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	13.8	
set_pin_physical_constraints	-pin_name	{AFC_OTWN[5]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	14.4	
set_pin_physical_constraints	-pin_name	{AFC_OTWN[4]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	15		
set_pin_physical_constraints	-pin_name	{AFC_OTWN[3]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	15.6	
set_pin_physical_constraints	-pin_name	{AFC_OTWN[2]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	16.2	
set_pin_physical_constraints	-pin_name	{AFC_OTWN[1]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	16.8	
set_pin_physical_constraints	-pin_name	{AFC_OTWN[0]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	17.4	
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[8]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	18		
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[7]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	18.6	
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[6]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	19.2	
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[5]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	19.8	
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[4]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	20.4	
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[3]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	21		
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[2]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	21.6	
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[1]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	22.2	
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[0]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	22.8	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[6]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	25.2	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[5]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	25.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[4]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	26.4	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[3]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	27		
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[2]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	27.6	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[1]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	28.2	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[0]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	28.8

set_pin_physical_constraints	-pin_name	{SPI_FCW_O[16]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	40.2	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[15]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	40.8	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[14]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	41.4	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[13]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	42		
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[12]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	42.6	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[11]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	43.2	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[10]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	43.8	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[9]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	44.4	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[8]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	45		
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[7]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	45.6	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[6]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	46.2	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[5]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	46.8	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[4]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	47.4	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[3]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	48		
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[2]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	48.6	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[1]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	49.2	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[0]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	49.8	
                                                                                                                          
set_pin_physical_constraints	-pin_name	{REF}					-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	6		
set_pin_physical_constraints	-pin_name	{CKVD}					-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	6.6		
