set_pin_physical_constraints	-pin_name	{SPI_NARST}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	30
set_pin_physical_constraints	-pin_name	{SPI_CONFIG}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	30.6
set_pin_physical_constraints	-pin_name	{SPI_PLL_EN}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	31.2
set_pin_physical_constraints	-pin_name	{SPI_DIGRST}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	31.8
set_pin_physical_constraints	-pin_name	{SPI_AFC_EN}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	32.4
set_pin_physical_constraints	-pin_name	{SPI_FAFC_EN}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	33
set_pin_physical_constraints	-pin_name	{SPI_CTRL}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	33.6
set_pin_physical_constraints	-pin_name	{SPI_PHESIG_GEN_EN}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	34.2
set_pin_physical_constraints	-pin_name	{SPI_DTC_GAINCAL_EN}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	34.8
set_pin_physical_constraints	-pin_name	{SPI_DTC_EN}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	35.4
set_pin_physical_constraints	-pin_name	{SPI_MMD_EN}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	36
set_pin_physical_constraints	-pin_name	{SPI_DSM_EN}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	36.6
set_pin_physical_constraints	-pin_name	{SPI_PDS_EN}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	37.2
set_pin_physical_constraints	-pin_name	{SPI_DN_EN}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	37.8
set_pin_physical_constraints	-pin_name	{SPI_SPD_EN}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	38.4
set_pin_physical_constraints	-pin_name	{SPI_PFD_EN}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	39
set_pin_physical_constraints	-pin_name	{SPI_CP_EN}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	39.6
set_pin_physical_constraints	-pin_name	{SPI_PRECHARGE_EN}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	40.2
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[12]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	40.8
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[11]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	41.4
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[10]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	42
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[9]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	42.6
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[8]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	43.2
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[7]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	43.8
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[6]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	44.4
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[5]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	45
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[4]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	45.6
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[3]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	46.2
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[2]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	46.8
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[1]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	47.4
set_pin_physical_constraints	-pin_name	{SPI_KDTCA_INIT[0]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	48
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[12]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	48.6
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[11]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	52.2
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[10]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	52.8
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[9]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	53.4
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[8]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	54
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[7]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	54.6
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[6]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	55.2
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[5]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	55.8
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[4]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	56.4
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[3]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	57
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[2]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	57.6
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[1]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	58.2
set_pin_physical_constraints	-pin_name	{SPI_KDTCB_INIT[0]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	58.8
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[12]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	59.4
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[11]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	60
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[10]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	60.6
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[9]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	61.2
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[8]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	61.8
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[7]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	62.4
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[6]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	63
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[5]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	63.6
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[4]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	64.2
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[3]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	64.8
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[2]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	65.4
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[1]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	66
set_pin_physical_constraints	-pin_name	{SPI_KDTCC_INIT[0]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	66.6
set_pin_physical_constraints	-pin_name	{SPI_KA[4]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	67.2
set_pin_physical_constraints	-pin_name	{SPI_KA[3]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	67.8
set_pin_physical_constraints	-pin_name	{SPI_KA[2]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	68.4
set_pin_physical_constraints	-pin_name	{SPI_KA[1]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	69
set_pin_physical_constraints	-pin_name	{SPI_KA[0]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	69.6
set_pin_physical_constraints	-pin_name	{SPI_KB[4]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	70.2
set_pin_physical_constraints	-pin_name	{SPI_KB[3]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	70.8
set_pin_physical_constraints	-pin_name	{SPI_KB[2]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	74.4
set_pin_physical_constraints	-pin_name	{SPI_KB[1]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	75
set_pin_physical_constraints	-pin_name	{SPI_KB[0]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	75.6
set_pin_physical_constraints	-pin_name	{SPI_KC[4]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	76.2
set_pin_physical_constraints	-pin_name	{SPI_KC[3]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	76.8
set_pin_physical_constraints	-pin_name	{SPI_KC[2]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	77.4
set_pin_physical_constraints	-pin_name	{SPI_KC[1]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	78
set_pin_physical_constraints	-pin_name	{SPI_KC[0]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	78.6
set_pin_physical_constraints	-pin_name	{SPI_ALPHA[3]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	79.2
set_pin_physical_constraints	-pin_name	{SPI_ALPHA[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	79.8
set_pin_physical_constraints	-pin_name	{SPI_ALPHA[1]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	80.4
set_pin_physical_constraints	-pin_name	{SPI_ALPHA[0]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	81
set_pin_physical_constraints	-pin_name	{SPI_DN_WEIGHT[4]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	81.6
set_pin_physical_constraints	-pin_name	{SPI_DN_WEIGHT[3]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	82.2
set_pin_physical_constraints	-pin_name	{SPI_DN_WEIGHT[2]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	82.8
set_pin_physical_constraints	-pin_name	{SPI_DN_WEIGHT[1]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	83.4
set_pin_physical_constraints	-pin_name	{SPI_DN_WEIGHT[0]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	84
set_pin_physical_constraints	-pin_name	{SPI_CALIORDER[2]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	84.6
set_pin_physical_constraints	-pin_name	{SPI_CALIORDER[1]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	85.2
set_pin_physical_constraints	-pin_name	{SPI_CALIORDER[0]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	85.8
set_pin_physical_constraints	-pin_name	{SPI_PSEC[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	86.4
set_pin_physical_constraints	-pin_name	{SPI_PSEC[1]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	87
set_pin_physical_constraints	-pin_name	{SPI_PSEC[0]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	87.6
set_pin_physical_constraints	-pin_name	{SPI_SECSEL_TEST[1]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	88.2
set_pin_physical_constraints	-pin_name	{SPI_SECSEL_TEST[0]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	88.8
set_pin_physical_constraints	-pin_name	{SPI_REGSEL_TEST[3]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	89.4
set_pin_physical_constraints	-pin_name	{SPI_REGSEL_TEST[2]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	90
set_pin_physical_constraints	-pin_name	{SPI_REGSEL_TEST[1]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	90.6
set_pin_physical_constraints	-pin_name	{SPI_REGSEL_TEST[0]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	91.2
set_pin_physical_constraints	-pin_name	{SPI_CAL_MODE}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	91.8
set_pin_physical_constraints	-pin_name	{SPI_CP[8]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	92.4
set_pin_physical_constraints	-pin_name	{SPI_CP[7]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	93
set_pin_physical_constraints	-pin_name	{SPI_CP[6]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	96.6
set_pin_physical_constraints	-pin_name	{SPI_CP[5]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	97.2
set_pin_physical_constraints	-pin_name	{SPI_CP[4]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	97.8
set_pin_physical_constraints	-pin_name	{SPI_CP[3]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	98.4
set_pin_physical_constraints	-pin_name	{SPI_CP[2]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	99
set_pin_physical_constraints	-pin_name	{SPI_CP[1]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	99.6
set_pin_physical_constraints	-pin_name	{SPI_CP[0]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	100.2
set_pin_physical_constraints	-pin_name	{SPI_CS[8]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	100.8
set_pin_physical_constraints	-pin_name	{SPI_CS[7]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	101.4
set_pin_physical_constraints	-pin_name	{SPI_CS[6]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	102
set_pin_physical_constraints	-pin_name	{SPI_CS[5]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	102.6
set_pin_physical_constraints	-pin_name	{SPI_CS[4]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	103.2
set_pin_physical_constraints	-pin_name	{SPI_CS[3]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	103.8
set_pin_physical_constraints	-pin_name	{SPI_CS[2]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	104.4
set_pin_physical_constraints	-pin_name	{SPI_CS[1]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	105
set_pin_physical_constraints	-pin_name	{SPI_CS[0]}					-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	105.6
set_pin_physical_constraints	-pin_name	{SPI_OTWSOURCE}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	106.2
set_pin_physical_constraints	-pin_name	{SPI_OTWSEL[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	106.8
set_pin_physical_constraints	-pin_name	{SPI_OTWSEL[1]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	107.4
set_pin_physical_constraints	-pin_name	{SPI_OTWSEL[0]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	108
set_pin_physical_constraints	-pin_name	{SPI_SNPCNTTDC_EN}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	108.6
set_pin_physical_constraints	-pin_name	{SPI_CNTPREDIV_EN}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	109.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI[6]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	109.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI[5]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	110.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI[4]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	111
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI[3]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	111.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI[2]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	112.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI[1]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	112.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI[0]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	113.4
set_pin_physical_constraints	-pin_name	{SPI_MMD_P[8]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	114
set_pin_physical_constraints	-pin_name	{SPI_MMD_P[7]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	114.6
set_pin_physical_constraints	-pin_name	{SPI_MMD_P[6]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	115.2
set_pin_physical_constraints	-pin_name	{SPI_MMD_P[5]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	118.8
set_pin_physical_constraints	-pin_name	{SPI_MMD_P[4]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	119.4
set_pin_physical_constraints	-pin_name	{SPI_MMD_P[3]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	120
set_pin_physical_constraints	-pin_name	{SPI_MMD_P[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	120.6
set_pin_physical_constraints	-pin_name	{SPI_MMD_P[1]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	121.2
set_pin_physical_constraints	-pin_name	{SPI_MMD_P[0]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	121.8
set_pin_physical_constraints	-pin_name	{SPI_MMD_S[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	122.4
set_pin_physical_constraints	-pin_name	{SPI_MMD_S[1]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	123
set_pin_physical_constraints	-pin_name	{SPI_MMD_S[0]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	123.6
set_pin_physical_constraints	-pin_name	{SPI_LO_PHASECAL_EN}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	124.2
set_pin_physical_constraints	-pin_name	{SPI_LO_DIV[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	124.8
set_pin_physical_constraints	-pin_name	{SPI_LO_DIV[1]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	125.4
set_pin_physical_constraints	-pin_name	{SPI_LO_DIV[0]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	126
set_pin_physical_constraints	-pin_name	{SPI_LO_PCALI_KI[4]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	126.6
set_pin_physical_constraints	-pin_name	{SPI_LO_PCALI_KI[3]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	127.2
set_pin_physical_constraints	-pin_name	{SPI_LO_PCALI_KI[2]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	127.8
set_pin_physical_constraints	-pin_name	{SPI_LO_PCALI_KI[1]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	128.4
set_pin_physical_constraints	-pin_name	{SPI_LO_PCALI_KI[0]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	129
set_pin_physical_constraints	-pin_name	{SPI_LO_PCALI_DN_EN}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	129.6
set_pin_physical_constraints	-pin_name	{KDTC_INT[12]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	130.2
set_pin_physical_constraints	-pin_name	{KDTC_INT[11]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	130.8
set_pin_physical_constraints	-pin_name	{KDTC_INT[10]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	131.4
set_pin_physical_constraints	-pin_name	{KDTC_INT[9]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	132
set_pin_physical_constraints	-pin_name	{KDTC_INT[8]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	132.6
set_pin_physical_constraints	-pin_name	{KDTC_INT[7]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	133.2
set_pin_physical_constraints	-pin_name	{KDTC_INT[6]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	133.8
set_pin_physical_constraints	-pin_name	{KDTC_INT[5]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	134.4
set_pin_physical_constraints	-pin_name	{KDTC_INT[4]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	135
set_pin_physical_constraints	-pin_name	{KDTC_INT[3]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	135.6
set_pin_physical_constraints	-pin_name	{KDTC_INT[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	136.2
set_pin_physical_constraints	-pin_name	{KDTC_INT[1]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	136.8
set_pin_physical_constraints	-pin_name	{KDTC_INT[0]}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	137.4
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[15]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	141
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[14]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	141.6
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[13]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	142.2
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[12]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	142.8
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[11]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	143.4
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[10]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	144
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[9]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	144.6
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[8]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	145.2
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[7]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	145.8
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[6]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	146.4
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[5]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	147
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[4]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	147.6
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[3]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	148.2
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[2]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	148.8
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[1]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	149.4
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM[0]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	150
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN[7]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	150.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN[6]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	151.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN[5]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	151.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN[4]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	152.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN[3]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	153
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN[2]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	153.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN[1]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	154.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN[0]}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	154.8
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI[4]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	155.4
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI[3]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	156
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI[2]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	156.6
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI[1]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	157.2
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI[0]}		-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	157.8
set_pin_physical_constraints	-pin_name	{SPI_AUXMMD_SEL}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	158.4
set_pin_physical_constraints	-pin_name	{SPI_LO_PCALI_KI_iir[0]}	-layers {M3}	-width	0.08	-depth	0	-side	1 -offset	159
set_pin_physical_constraints	-pin_name	{SPI_LO_PCALI_KI_iir[1]}	-layers {M3}    -width	0.08	-depth	0	-side	1 -offset	159.6
set_pin_physical_constraints	-pin_name	{SPI_LO_PCALI_KI_iir[2]}	-layers {M3}    -width	0.08	-depth	0	-side	1 -offset	163.2
set_pin_physical_constraints	-pin_name	{SPI_LO_PCALI_KI_iir[3]}	-layers {M3}    -width	0.08	-depth	0	-side	1 -offset	163.8
set_pin_physical_constraints	-pin_name	{SPI_LO_PCALI_KI_iir[4]}	-layers {M3}    -width	0.08	-depth	0	-side	1 -offset	164.4
set_pin_physical_constraints	-pin_name	{SPI_SYS_EDGE_SEL[0]}		-layers {M3}    -width	0.08	-depth	0	-side	1 -offset	165
set_pin_physical_constraints	-pin_name	{SPI_SYS_EDGE_SEL[1]}		-layers {M3}    -width	0.08	-depth	0	-side	1 -offset	165.6
set_pin_physical_constraints	-pin_name	{SPI_SYS_EDGE_SEL[2]}		-layers {M3}    -width	0.08	-depth	0	-side	1 -offset	166.2
set_pin_physical_constraints	-pin_name	{SPI_DSM_BOOTMODE}			-layers {M3}    -width	0.08	-depth	0	-side	1 -offset	166.8
set_pin_physical_constraints	-pin_name	{SPI_LO_PHASECAL_EN_SEL}	-layers {M3}    -width	0.08	-depth	0	-side	1 -offset	167.4
#up                                                                 	
set_pin_physical_constraints	-pin_name	{FAFC_CTRL}					-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	40
set_pin_physical_constraints	-pin_name	{FREQLOCK2}					-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	40.6
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[8]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	41.2
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[7]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	41.8
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[6]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	42.4
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[5]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	43
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[4]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	43.6
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[3]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	44.2
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[2]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	44.8
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[1]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	45.4
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[0]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	46
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[8]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	46.6
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[7]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	47.2
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[6]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	47.8
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[5]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	48.4
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[4]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	49
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[3]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	49.6
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[2]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	50.2
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[1]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	50.8
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[0]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	51.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[34]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	52
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[33]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	52.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[32]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	53.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[31]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	53.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[30]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	54.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[29]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	55
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[28]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	55.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[27]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	56.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[26]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	56.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[25]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	57.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[24]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	58
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[23]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	58.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[22]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	59.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[21]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	59.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[20]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	60.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[19]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	61
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[18]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	61.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[17]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	62.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[16]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	62.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[15]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	63.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[14]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	64
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[13]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	64.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[12]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	65.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[11]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	65.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[10]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	66.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[9]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	67
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[8]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	67.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[7]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	68.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[6]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	68.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[5]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	69.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[4]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	70
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[3]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	70.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[2]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	71.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[1]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	71.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[0]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	72.4
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI_O[4]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	73
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI_O[3]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	73.6
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI_O[2]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	74.2
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI_O[1]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	74.8
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI_O[0]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	75.4
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[15]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	76
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[14]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	76.6
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[13]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	77.2
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[12]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	77.8
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[11]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	78.4
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[10]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	79
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[9]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	79.6
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[8]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	80.2
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[7]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	80.8
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[6]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	81.4
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[5]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	82
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[4]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	82.6
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[3]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	83.2
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[2]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	83.8
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[1]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	84.4
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[0]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	85
set_pin_physical_constraints	-pin_name	{SPI_AUXMMD_SEL_O}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	85.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[7]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	86.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[6]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	86.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[5]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	87.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[4]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	88
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[3]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	88.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[2]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	89.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[1]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	89.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[0]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	90.4
																		
set_pin_physical_constraints	-pin_name	{AFC_CTRL}					-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	277.9
set_pin_physical_constraints	-pin_name	{FREQLOCK}					-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	278.5
set_pin_physical_constraints	-pin_name	{AFC_OTWP[8]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	279.1
set_pin_physical_constraints	-pin_name	{AFC_OTWP[7]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	279.7
set_pin_physical_constraints	-pin_name	{AFC_OTWP[6]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	280.3
set_pin_physical_constraints	-pin_name	{AFC_OTWP[5]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	280.9
set_pin_physical_constraints	-pin_name	{AFC_OTWP[4]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	281.5
set_pin_physical_constraints	-pin_name	{AFC_OTWP[3]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	282.1
set_pin_physical_constraints	-pin_name	{AFC_OTWP[2]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	282.7
set_pin_physical_constraints	-pin_name	{AFC_OTWP[1]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	283.3
set_pin_physical_constraints	-pin_name	{AFC_OTWP[0]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	283.9
set_pin_physical_constraints	-pin_name	{AFC_OTWN[8]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	284.5
set_pin_physical_constraints	-pin_name	{AFC_OTWN[7]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	285.1
set_pin_physical_constraints	-pin_name	{AFC_OTWN[6]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	285.7
set_pin_physical_constraints	-pin_name	{AFC_OTWN[5]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	286.3
set_pin_physical_constraints	-pin_name	{AFC_OTWN[4]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	286.9
set_pin_physical_constraints	-pin_name	{AFC_OTWN[3]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	287.5
set_pin_physical_constraints	-pin_name	{AFC_OTWN[2]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	288.1
set_pin_physical_constraints	-pin_name	{AFC_OTWN[1]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	288.7
set_pin_physical_constraints	-pin_name	{AFC_OTWN[0]}				-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	289.3
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[8]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	289.9
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[7]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	290.5
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[6]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	291.1
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[5]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	291.7
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[4]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	292.3
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[3]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	292.9
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[2]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	293.5
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[1]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	294.1
set_pin_physical_constraints	-pin_name	{SPI_MMD_P_O[0]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	294.7
set_pin_physical_constraints	-pin_name	{SPI_MMD_S_O[2]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	295.3
set_pin_physical_constraints	-pin_name	{SPI_MMD_S_O[1]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	295.9
set_pin_physical_constraints	-pin_name	{SPI_MMD_S_O[0]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	296.5
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[6]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	297.1
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[5]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	297.7
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[4]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	298.3
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[3]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	298.9
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[2]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	299.5
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[1]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	300.1
set_pin_physical_constraints	-pin_name	{SPI_FCW_MULTI_O[0]}		-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	300.7
																		
set_pin_physical_constraints	-pin_name	{CKVD}						-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	350	
#right                                                              	
set_pin_physical_constraints	-pin_name	{PHE_SIG}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	150.6	
set_pin_physical_constraints	-pin_name	{PHE_SIG2}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	151.2	
set_pin_physical_constraints	-pin_name	{LO_STATE[1]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	151.8	
set_pin_physical_constraints	-pin_name	{LO_STATE[0]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	152.4	
set_pin_physical_constraints	-pin_name	{VDACCTRL_OUTP[1]}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	153		
set_pin_physical_constraints	-pin_name	{VDACCTRL_OUTP[0]}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	153.6	
set_pin_physical_constraints	-pin_name	{VDACCTRL_OUTN[1]}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	154.2	
set_pin_physical_constraints	-pin_name	{VDACCTRL_OUTN[0]}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	154.8	
set_pin_physical_constraints	-pin_name	{DCW_DELAY[11]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	155.4	
set_pin_physical_constraints	-pin_name	{DCW_DELAY[10]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	156		
set_pin_physical_constraints	-pin_name	{DCW_DELAY[9]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	156.6	
set_pin_physical_constraints	-pin_name	{DCW_DELAY[8]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	157.2	
set_pin_physical_constraints	-pin_name	{DCW_DELAY[7]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	157.8	
set_pin_physical_constraints	-pin_name	{DCW_DELAY[6]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	158.4	
set_pin_physical_constraints	-pin_name	{DCW_DELAY[5]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	159		
set_pin_physical_constraints	-pin_name	{DCW_DELAY[4]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	159.6	
set_pin_physical_constraints	-pin_name	{DCW_DELAY[3]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	160.2	
set_pin_physical_constraints	-pin_name	{DCW_DELAY[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	160.8	
set_pin_physical_constraints	-pin_name	{DCW_DELAY[1]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	161.4	
set_pin_physical_constraints	-pin_name	{DCW_DELAY[0]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	162		
set_pin_physical_constraints	-pin_name	{O_MMD_P[8]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	162.6	
set_pin_physical_constraints	-pin_name	{O_MMD_P[7]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	163.2	
set_pin_physical_constraints	-pin_name	{O_MMD_P[6]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	163.8	
set_pin_physical_constraints	-pin_name	{O_MMD_P[5]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	164.4	
set_pin_physical_constraints	-pin_name	{O_MMD_P[4]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	165		
set_pin_physical_constraints	-pin_name	{O_MMD_P[3]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	165.6	
set_pin_physical_constraints	-pin_name	{O_MMD_P[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	166.2	
set_pin_physical_constraints	-pin_name	{O_MMD_P[1]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	166.8	
set_pin_physical_constraints	-pin_name	{O_MMD_P[0]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	167.4	
set_pin_physical_constraints	-pin_name	{O_MMD_S[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	168		
set_pin_physical_constraints	-pin_name	{O_MMD_S[1]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	168.6	
set_pin_physical_constraints	-pin_name	{O_MMD_S[0]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	169.2	
set_pin_physical_constraints	-pin_name	{O_CP[8]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	169.8	
set_pin_physical_constraints	-pin_name	{O_CP[7]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	170.4	
set_pin_physical_constraints	-pin_name	{O_CP[6]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	171		
set_pin_physical_constraints	-pin_name	{O_CP[5]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	171.6	
set_pin_physical_constraints	-pin_name	{O_CP[4]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	172.2	
set_pin_physical_constraints	-pin_name	{O_CP[3]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	172.8	
set_pin_physical_constraints	-pin_name	{O_CP[2]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	173.4	
set_pin_physical_constraints	-pin_name	{O_CP[1]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	174		
set_pin_physical_constraints	-pin_name	{O_CP[0]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	174.6	
set_pin_physical_constraints	-pin_name	{O_CS[8]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	175.2	
set_pin_physical_constraints	-pin_name	{O_CS[7]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	175.8	
set_pin_physical_constraints	-pin_name	{O_CS[6]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	176.4	
set_pin_physical_constraints	-pin_name	{O_CS[5]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	177		
set_pin_physical_constraints	-pin_name	{O_CS[4]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	177.6	
set_pin_physical_constraints	-pin_name	{O_CS[3]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	178.2	
set_pin_physical_constraints	-pin_name	{O_CS[2]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	178.8	
set_pin_physical_constraints	-pin_name	{O_CS[1]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	179.4	
set_pin_physical_constraints	-pin_name	{O_CS[0]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	180		
set_pin_physical_constraints	-pin_name	{O_CP_N[8]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	180.6	
set_pin_physical_constraints	-pin_name	{O_CP_N[7]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	181.2	
set_pin_physical_constraints	-pin_name	{O_CP_N[6]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	181.8	
set_pin_physical_constraints	-pin_name	{O_CP_N[5]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	182.4	
set_pin_physical_constraints	-pin_name	{O_CP_N[4]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	183		
set_pin_physical_constraints	-pin_name	{O_CP_N[3]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	183.6	
set_pin_physical_constraints	-pin_name	{O_CP_N[2]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	184.2	
set_pin_physical_constraints	-pin_name	{O_CP_N[1]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	184.8	
set_pin_physical_constraints	-pin_name	{O_CP_N[0]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	185.4	
set_pin_physical_constraints	-pin_name	{O_CS_N[8]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	186		
set_pin_physical_constraints	-pin_name	{O_CS_N[7]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	186.6	
set_pin_physical_constraints	-pin_name	{O_CS_N[6]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	187.2	
set_pin_physical_constraints	-pin_name	{O_CS_N[5]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	187.8	
set_pin_physical_constraints	-pin_name	{O_CS_N[4]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	188.4	
set_pin_physical_constraints	-pin_name	{O_CS_N[3]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	189		
set_pin_physical_constraints	-pin_name	{O_CS_N[2]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	189.6	
set_pin_physical_constraints	-pin_name	{O_CS_N[1]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	190.2	
set_pin_physical_constraints	-pin_name	{O_CS_N[0]}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	190.8	
set_pin_physical_constraints	-pin_name	{SPI_OTWSEL_O[2]}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	191.4	
set_pin_physical_constraints	-pin_name	{SPI_OTWSEL_O[1]}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	192		
set_pin_physical_constraints	-pin_name	{SPI_OTWSEL_O[0]}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	192.6	
set_pin_physical_constraints	-pin_name	{O_PHESIG_GEN_EN}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	193.2	
set_pin_physical_constraints	-pin_name	{O_DTC_GAINCAL_EN}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	193.8	
set_pin_physical_constraints	-pin_name	{O_DN_EN}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	194.4	
set_pin_physical_constraints	-pin_name	{O_DTC_EN}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	195		
set_pin_physical_constraints	-pin_name	{O_MMD_EN}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	195.6	
set_pin_physical_constraints	-pin_name	{O_DSM_EN}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	196.2	
set_pin_physical_constraints	-pin_name	{O_PDS_EN}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	196.8	
set_pin_physical_constraints	-pin_name	{O_PRECHARGE_EN}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	197.4	
set_pin_physical_constraints	-pin_name	{O_PFD_EN}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	198		
set_pin_physical_constraints	-pin_name	{O_CP_EN}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	198.6	
set_pin_physical_constraints	-pin_name	{O_SPD_EN}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	199.2	
set_pin_physical_constraints	-pin_name	{O_SNPCNTTDC_EN}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	199.8	
set_pin_physical_constraints	-pin_name	{O_CNTPREDIV_EN}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	200.4	
set_pin_physical_constraints	-pin_name	{SYNC_EN}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	201		
set_pin_physical_constraints	-pin_name	{SYNC_REF}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	201.6	
#down                                                               	
set_pin_physical_constraints	-pin_name	{FLOCK}						-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	100
set_pin_physical_constraints	-pin_name	{SPI_FCW[34]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	30.6
set_pin_physical_constraints	-pin_name	{SPI_FCW[33]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	31.2
set_pin_physical_constraints	-pin_name	{SPI_FCW[32]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	31.8
set_pin_physical_constraints	-pin_name	{SPI_FCW[31]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	32.4
set_pin_physical_constraints	-pin_name	{SPI_FCW[30]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	33
set_pin_physical_constraints	-pin_name	{SPI_FCW[29]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	33.6
set_pin_physical_constraints	-pin_name	{SPI_FCW[28]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	34.2
set_pin_physical_constraints	-pin_name	{SPI_FCW[27]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	34.8
set_pin_physical_constraints	-pin_name	{SPI_FCW[26]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	35.4
set_pin_physical_constraints	-pin_name	{SPI_FCW[25]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	36
set_pin_physical_constraints	-pin_name	{SPI_FCW[24]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	36.6
set_pin_physical_constraints	-pin_name	{SPI_FCW[23]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	37.2
set_pin_physical_constraints	-pin_name	{SPI_FCW[22]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	37.8
set_pin_physical_constraints	-pin_name	{SPI_FCW[21]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	38.4
set_pin_physical_constraints	-pin_name	{SPI_FCW[20]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	39
set_pin_physical_constraints	-pin_name	{SPI_FCW[19]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	39.6
set_pin_physical_constraints	-pin_name	{SPI_FCW[18]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	40.2
set_pin_physical_constraints	-pin_name	{SPI_FCW[17]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	40.8
set_pin_physical_constraints	-pin_name	{SPI_FCW[16]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	41.4
set_pin_physical_constraints	-pin_name	{SPI_FCW[15]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	42
set_pin_physical_constraints	-pin_name	{SPI_FCW[14]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	42.6
set_pin_physical_constraints	-pin_name	{SPI_FCW[13]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	43.2
set_pin_physical_constraints	-pin_name	{SPI_FCW[12]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	43.8
set_pin_physical_constraints	-pin_name	{SPI_FCW[11]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	44.4
set_pin_physical_constraints	-pin_name	{SPI_FCW[10]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	45
set_pin_physical_constraints	-pin_name	{SPI_FCW[9]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	45.6
set_pin_physical_constraints	-pin_name	{SPI_FCW[8]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	46.2
set_pin_physical_constraints	-pin_name	{SPI_FCW[7]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	46.8
set_pin_physical_constraints	-pin_name	{SPI_FCW[6]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	47.4
set_pin_physical_constraints	-pin_name	{SPI_FCW[5]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	48
set_pin_physical_constraints	-pin_name	{SPI_FCW[4]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	48.6
set_pin_physical_constraints	-pin_name	{SPI_FCW[3]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	49.2
set_pin_physical_constraints	-pin_name	{SPI_FCW[2]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	49.8
set_pin_physical_constraints	-pin_name	{SPI_FCW[1]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	50.4
set_pin_physical_constraints	-pin_name	{SPI_FCW[0]}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	51
set_pin_physical_constraints	-pin_name	{LO_PHASECAL_EN_LO}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	51.6