#up
set_pin_physical_constraints	-pin_name	{CNT7BIT[6]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	6.6
set_pin_physical_constraints	-pin_name	{CNT7BIT[5]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	7.2
set_pin_physical_constraints	-pin_name	{CNT7BIT[4]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	7.8
set_pin_physical_constraints	-pin_name	{CNT7BIT[3]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	8.4
set_pin_physical_constraints	-pin_name	{CNT7BIT[2]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	9
set_pin_physical_constraints	-pin_name	{CNT7BIT[1]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	9.6
set_pin_physical_constraints	-pin_name	{CNT7BIT[0]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	10.2
set_pin_physical_constraints	-pin_name	{TDCCODE[5]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	10.8
set_pin_physical_constraints	-pin_name	{TDCCODE[4]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	11.4
set_pin_physical_constraints	-pin_name	{TDCCODE[3]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	12
set_pin_physical_constraints	-pin_name	{TDCCODE[2]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	12.6
set_pin_physical_constraints	-pin_name	{TDCCODE[1]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	13.2
set_pin_physical_constraints	-pin_name	{TDCCODE[0]}			-layers	{M4}	-width	0.08	-depth	0	-side	2 -offset	13.8
#left
set_pin_physical_constraints	-pin_name	{SPI_FAFC_EN}			-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	6		
set_pin_physical_constraints	-pin_name	{SPI_NARST}				-layers	{M3}	-width	0.08	-depth	0	-side	1 -offset	6.6		
#right
set_pin_physical_constraints	-pin_name	{REF}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	6
set_pin_physical_constraints	-pin_name	{MMDNRST_FAFC}			-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	6.6
set_pin_physical_constraints	-pin_name	{QN1S[7]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	7.2
set_pin_physical_constraints	-pin_name	{QN1S[6]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	7.8
set_pin_physical_constraints	-pin_name	{QN1S[5]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	8.4
set_pin_physical_constraints	-pin_name	{QN1S[4]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	9
set_pin_physical_constraints	-pin_name	{QN1S[3]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	9.6
set_pin_physical_constraints	-pin_name	{QN1S[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	10.2
set_pin_physical_constraints	-pin_name	{QN2S[7]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	10.8
set_pin_physical_constraints	-pin_name	{QN2S[6]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	11.4
set_pin_physical_constraints	-pin_name	{QN2S[5]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	12
set_pin_physical_constraints	-pin_name	{QN2S[4]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	12.6
set_pin_physical_constraints	-pin_name	{QN2S[3]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	13.2
set_pin_physical_constraints	-pin_name	{QN2S[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	13.8
set_pin_physical_constraints	-pin_name	{QP1S[7]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	14.4
set_pin_physical_constraints	-pin_name	{QP1S[6]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	15
set_pin_physical_constraints	-pin_name	{QP1S[5]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	15.6
set_pin_physical_constraints	-pin_name	{QP1S[4]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	16.2
set_pin_physical_constraints	-pin_name	{QP1S[3]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	16.8
set_pin_physical_constraints	-pin_name	{QP1S[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	17.4
set_pin_physical_constraints	-pin_name	{QP2S[7]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	18
set_pin_physical_constraints	-pin_name	{QP2S[6]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	18.6
set_pin_physical_constraints	-pin_name	{QP2S[5]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	19.2
set_pin_physical_constraints	-pin_name	{QP2S[4]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	19.8
set_pin_physical_constraints	-pin_name	{QP2S[3]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	20.4
set_pin_physical_constraints	-pin_name	{QP2S[2]}				-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	21  
set_pin_physical_constraints	-pin_name	{NRST2}					-layers	{M3}	-width	0.08	-depth	0	-side	3 -offset	21.6
#down
set_pin_physical_constraints	-pin_name	{FAFC_CTRL}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	40
set_pin_physical_constraints	-pin_name	{FREQLOCK2}				-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	40.6	
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[8]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	41.2	
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[7]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	41.8	
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[6]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	42.4	
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[5]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	43		
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[4]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	43.6	
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[3]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	44.2	
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[2]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	44.8	
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[1]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	45.4	
set_pin_physical_constraints	-pin_name	{FAFC_OTWP[0]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	46		
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[8]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	46.6	
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[7]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	47.2	
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[6]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	47.8	
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[5]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	48.4	
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[4]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	49		
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[3]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	49.6	
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[2]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	50.2	
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[1]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	50.8	
set_pin_physical_constraints	-pin_name	{FAFC_OTWN[0]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	51.4	
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[24]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	52
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[23]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	52.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[22]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	53.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[21]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	53.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[20]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	54.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[19]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	55
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[18]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	55.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[17]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	56.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[16]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	56.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[15]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	57.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[14]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	58
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[13]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	58.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[12]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	59.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[11]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	59.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[10]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	60.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[9]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	61
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[8]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	61.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[7]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	62.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[6]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	62.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[5]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	63.4
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[4]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	64
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[3]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	64.6
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[2]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	65.2
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[1]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	65.8
set_pin_physical_constraints	-pin_name	{SPI_FCW_O[0]}			-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	66.4
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI_O[4]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	73		
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI_O[3]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	73.6	
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI_O[2]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	74.2	
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI_O[1]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	74.8	
set_pin_physical_constraints	-pin_name	{SPI_FAFC_FMULTI_O[0]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	75.4	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[15]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	76		
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[14]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	76.6	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[13]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	77.2	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[12]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	77.8	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[11]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	78.4	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[10]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	79		
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[9]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	79.6	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[8]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	80.2	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[7]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	80.8	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[6]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	81.4	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[5]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	82		
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[4]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	82.6	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[3]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	83.2	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[2]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	83.8	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[1]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	84.4	
set_pin_physical_constraints	-pin_name	{SPI_TDCRESNORM_O[0]}	-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	85		
set_pin_physical_constraints	-pin_name	{SPI_AUXMMD_SEL_O}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	85.6	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[7]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	86.2	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[6]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	86.8	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[5]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	87.4	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[4]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	88		
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[3]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	88.6	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[2]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	89.2	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[1]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	89.8	
set_pin_physical_constraints	-pin_name	{SPI_FCW_MGN_O[0]}		-layers	{M4}	-width	0.08	-depth	0	-side	4 -offset	90.4	