set_pin_physical_constraints -pin_name {AFC_CTRL} -offset 140 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {FREQLOCK} -offset 140.6 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWP[8]} -offset 141.2 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWP[7]} -offset 141.8 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWP[6]} -offset 142.4 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWP[5]} -offset 143 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWP[4]} -offset 143.6 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWP[3]} -offset 144.2 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWP[2]} -offset 144.8 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWP[1]} -offset 145.4 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWP[0]} -offset 146 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWN[8]} -offset 146.6 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWN[7]} -offset 147.2 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWN[6]} -offset 147.8 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWN[5]} -offset 148.4 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWN[4]} -offset 149 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWN[3]} -offset 149.6 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWN[2]} -offset 150.2 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWN[1]} -offset 150.8 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {AFC_OTWN[0]} -offset 151.4 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[8]} -offset 152 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[7]} -offset 152.6 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[6]} -offset 153.2 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[5]} -offset 153.8 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[4]} -offset 154.4 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[3]} -offset 155 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[2]} -offset 155.6 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[1]} -offset 156.2 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[0]} -offset 156.8 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_S_O[2]} -offset 157.4 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_S_O[1]} -offset 158 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_S_O[0]} -offset 158.6 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[6]} -offset 159.2 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[5]} -offset 159.8 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[4]} -offset 160.4 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[3]} -offset 161 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[2]} -offset 161.6 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[1]} -offset 162.2 -layers {M3} -width 0.1 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[0]} -offset 162.8 -layers {M3} -width 0.1 -depth 0 -side 1


set_pin_physical_constraints -pin_name {SPI_CONFIG} -offset 5.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PLL_EN} -offset 6.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DIGRST} -offset 6.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_AFC_EN} -offset 7.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FAFC_EN} -offset 8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CTRL} -offset 8.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PHESIG_GEN_EN} -offset 9.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DTC_GAINCAL_EN} -offset 9.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DTC_EN} -offset 10.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_EN} -offset 11 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DSM_EN} -offset 11.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_EN} -offset 12.2 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_SPD_EN} -offset 14 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PFD_EN} -offset 14.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP_EN} -offset 15.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PRECHARGE_EN} -offset 15.8 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_CS[6]} -offset 24.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[7]} -offset 24.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[8]} -offset 25.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[0]} -offset 26 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[1]} -offset 26.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[2]} -offset 27.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[3]} -offset 27.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[4]} -offset 28.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[5]} -offset 29 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[6]} -offset 29.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[7]} -offset 30.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CP[8]} -offset 30.8 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[0]} -offset 34.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[1]} -offset 35 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[2]} -offset 35.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[3]} -offset 36.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[4]} -offset 36.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[0]} -offset 37.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[1]} -offset 38 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[2]} -offset 38.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_ALPHA[3]} -offset 39.2 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_NARST} -offset 42.8 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_MMD_S[2]} -offset 46.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[0]} -offset 47 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[1]} -offset 47.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[2]} -offset 48.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[3]} -offset 48.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[4]} -offset 49.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[5]} -offset 50 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[6]} -offset 50.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[7]} -offset 51.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P[8]} -offset 51.8 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[0]} -offset 55.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[1]} -offset 56 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[2]} -offset 56.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[3]} -offset 57.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[4]} -offset 57.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[5]} -offset 58.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI[6]} -offset 59 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL[0]} -offset 59.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL[1]} -offset 60.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL[2]} -offset 60.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSOURCE} -offset 61.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[0]} -offset 62 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[1]} -offset 62.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[2]} -offset 63.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[3]} -offset 63.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[4]} -offset 64.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CS[5]} -offset 65 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[0]} -offset 68.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[1]} -offset 69.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[2]} -offset 69.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[3]} -offset 70.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[4]} -offset 71 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[5]} -offset 71.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[6]} -offset 72.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[7]} -offset 72.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[8]} -offset 73.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[9]} -offset 74 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[10]} -offset 74.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[11]} -offset 75.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[12]} -offset 75.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[0]} -offset 76.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[1]} -offset 77 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[2]} -offset 77.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[3]} -offset 78.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_SECSEL_TEST[0]} -offset 78.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_SECSEL_TEST[1]} -offset 79.4 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_LO_PHASECAL_EN} -offset 82.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_DN_EN} -offset 83 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_LO_DIV[0]} -offset 84.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_DIV[1]} -offset 84.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_DIV[2]} -offset 85.4 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_PDS_EN} -offset 90.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PSEC[0]} -offset 91.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PSEC[1]} -offset 92 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_PSEC[2]} -offset 92.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CAL_MODE} -offset 93.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CALIORDER[0]} -offset 93.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CALIORDER[1]} -offset 94.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CALIORDER[2]} -offset 95 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[0]} -offset 95.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[1]} -offset 96.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[2]} -offset 96.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[3]} -offset 97.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KA[4]} -offset 98 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KB[0]} -offset 98.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KB[1]} -offset 99.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KB[2]} -offset 99.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KB[3]} -offset 100.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KB[4]} -offset 101 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KC[0]} -offset 101.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KC[1]} -offset 102.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KC[2]} -offset 102.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KC[3]} -offset 103.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KC[4]} -offset 104 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[0]} -offset 104.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[1]} -offset 105.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[2]} -offset 105.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[3]} -offset 106.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI[4]} -offset 107 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[0]} -offset 113 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[1]} -offset 113.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[2]} -offset 114.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[3]} -offset 114.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[4]} -offset 115.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[5]} -offset 116 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[6]} -offset 116.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[7]} -offset 117.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[8]} -offset 117.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[9]} -offset 118.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[10]} -offset 119 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[11]} -offset 119.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[12]} -offset 120.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[0]} -offset 120.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[1]} -offset 121.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[2]} -offset 122 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[3]} -offset 122.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[4]} -offset 123.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[5]} -offset 123.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[6]} -offset 124.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[7]} -offset 125 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[8]} -offset 125.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[9]} -offset 126.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[10]} -offset 126.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[11]} -offset 127.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[12]} -offset 128 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[0]} -offset 128.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[1]} -offset 129.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[2]} -offset 129.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[3]} -offset 130.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_LO_PCALI_KI_iir[4]} -offset 131 -layers {M3} -width 0.1 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_SNPCNTTDC_EN} -offset 132.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_CNTPREDIV_EN} -offset 132.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_S[0]} -offset 133.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_S[1]} -offset 134 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[12]} -offset 134.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[11]} -offset 135.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[10]} -offset 135.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[9]} -offset 136.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[8]} -offset 137 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[7]} -offset 137.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[6]} -offset 138.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[5]} -offset 138.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[4]} -offset 139.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[3]} -offset 140 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[2]} -offset 140.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[1]} -offset 141.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {KDTC_INT[0]} -offset 141.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {FLOCK} -offset 142.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {LO_PCALI_DONE} -offset 143 -layers {M3} -width 0.1 -depth 0 -side 3


set_pin_physical_constraints -pin_name {FAFC_CTRL} -offset 220 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FREQLOCK2} -offset 220.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWP[8]} -offset 221.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWP[7]} -offset 221.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWP[6]} -offset 222.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWP[5]} -offset 223 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWP[4]} -offset 223.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWP[3]} -offset 224.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWP[2]} -offset 224.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWP[1]} -offset 225.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWP[0]} -offset 226 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWN[8]} -offset 226.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWN[7]} -offset 227.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWN[6]} -offset 227.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWN[5]} -offset 228.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWN[4]} -offset 229 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWN[3]} -offset 229.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWN[2]} -offset 230.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWN[1]} -offset 230.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FAFC_OTWN[0]} -offset 231.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[34]} -offset 232 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[33]} -offset 232.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[32]} -offset 233.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[31]} -offset 233.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[30]} -offset 234.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[29]} -offset 235 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[28]} -offset 235.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[27]} -offset 236.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[26]} -offset 236.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[25]} -offset 237.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[24]} -offset 238 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[23]} -offset 238.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[22]} -offset 239.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[21]} -offset 239.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[20]} -offset 240.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[19]} -offset 241 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[18]} -offset 241.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[17]} -offset 242.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[16]} -offset 242.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[15]} -offset 243.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[14]} -offset 244 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[13]} -offset 244.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[12]} -offset 245.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[11]} -offset 245.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[10]} -offset 246.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[9]} -offset 247 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[8]} -offset 247.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[7]} -offset 248.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[6]} -offset 248.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[5]} -offset 249.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[4]} -offset 250 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[3]} -offset 250.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[2]} -offset 251.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[1]} -offset 251.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_O[0]} -offset 252.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI_O[4]} -offset 253 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI_O[3]} -offset 253.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI_O[2]} -offset 254.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI_O[1]} -offset 254.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI_O[0]} -offset 255.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[15]} -offset 256 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[14]} -offset 256.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[13]} -offset 257.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[12]} -offset 257.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[11]} -offset 258.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[10]} -offset 259 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[9]} -offset 259.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[8]} -offset 260.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[7]} -offset 260.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[6]} -offset 261.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[5]} -offset 262 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[4]} -offset 262.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[3]} -offset 263.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[2]} -offset 263.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[1]} -offset 264.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM_O[0]} -offset 265 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_AUXMMD_SEL_O} -offset 265.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[7]} -offset 266.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[6]} -offset 266.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[5]} -offset 267.4 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[4]} -offset 268 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[3]} -offset 268.6 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[2]} -offset 269.2 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[1]} -offset 269.8 -layers {M4} -width 0.1 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_FCW_MGN_O[0]} -offset 270.4 -layers {M4} -width 0.1 -depth 0 -side 2


set_pin_physical_constraints -pin_name {CKVD} -offset 240 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {PHE_SIG} -offset 240.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {PHE_SIG2} -offset 241.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {LO_STATE[1]} -offset 241.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {LO_STATE[0]} -offset 242.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {VDACCTRL_OUTP[1]} -offset 243 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {VDACCTRL_OUTP[0]} -offset 243.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {VDACCTRL_OUTN[1]} -offset 244.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {VDACCTRL_OUTN[0]} -offset 244.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[11]} -offset 245.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[10]} -offset 246 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[9]} -offset 246.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[8]} -offset 247.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[7]} -offset 247.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[6]} -offset 248.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[5]} -offset 249 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[4]} -offset 249.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[3]} -offset 250.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[2]} -offset 250.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[1]} -offset 251.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[0]} -offset 252 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[8]} -offset 252.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[7]} -offset 253.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[6]} -offset 253.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[5]} -offset 254.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[4]} -offset 255 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[3]} -offset 255.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[2]} -offset 256.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[1]} -offset 256.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[0]} -offset 257.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_S[2]} -offset 258 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_S[1]} -offset 258.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_S[0]} -offset 259.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[8]} -offset 259.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[7]} -offset 260.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[6]} -offset 261 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[5]} -offset 261.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[4]} -offset 262.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[3]} -offset 262.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[2]} -offset 263.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[1]} -offset 264 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[0]} -offset 264.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[8]} -offset 265.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[7]} -offset 265.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[6]} -offset 266.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[5]} -offset 267 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[4]} -offset 267.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[3]} -offset 268.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[2]} -offset 268.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[1]} -offset 269.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[0]} -offset 270 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[8]} -offset 270.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[7]} -offset 271.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[6]} -offset 271.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[5]} -offset 272.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[4]} -offset 273 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[3]} -offset 273.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[2]} -offset 274.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[1]} -offset 274.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[0]} -offset 275.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[8]} -offset 276 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[7]} -offset 276.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[6]} -offset 277.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[5]} -offset 277.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[4]} -offset 278.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[3]} -offset 279 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[2]} -offset 279.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[1]} -offset 280.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[0]} -offset 280.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL_O[2]} -offset 281.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL_O[1]} -offset 282 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL_O[0]} -offset 282.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_PHESIG_GEN_EN} -offset 283.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_DTC_GAINCAL_EN} -offset 283.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_DN_EN} -offset 284.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_DTC_EN} -offset 285 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_EN} -offset 285.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_DSM_EN} -offset 286.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_PDS_EN} -offset 286.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_PRECHARGE_EN} -offset 287.4 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_PFD_EN} -offset 288 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_EN} -offset 288.6 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_SPD_EN} -offset 289.2 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_SNPCNTTDC_EN} -offset 289.8 -layers {M3} -width 0.1 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CNTPREDIV_EN} -offset 290.4 -layers {M3} -width 0.1 -depth 0 -side 3


set_pin_physical_constraints -pin_name {SYNC_EN} -offset 80 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SYNC_REF} -offset 80.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[34]} -offset 81.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[33]} -offset 81.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[32]} -offset 82.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[31]} -offset 83 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[30]} -offset 83.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[29]} -offset 84.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[28]} -offset 84.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[27]} -offset 85.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[26]} -offset 86 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[25]} -offset 86.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[24]} -offset 87.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[23]} -offset 87.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[22]} -offset 88.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[21]} -offset 89 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[20]} -offset 89.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[19]} -offset 90.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[18]} -offset 90.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[17]} -offset 91.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[16]} -offset 92 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[15]} -offset 92.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[14]} -offset 93.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[13]} -offset 93.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[12]} -offset 94.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[11]} -offset 95 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[10]} -offset 95.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[9]} -offset 96.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[8]} -offset 96.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[7]} -offset 97.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[6]} -offset 98 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[5]} -offset 98.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[4]} -offset 99.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[3]} -offset 99.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[2]} -offset 100.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[1]} -offset 101 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW[0]} -offset 101.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI[4]} -offset 102.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI[3]} -offset 102.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI[2]} -offset 103.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI[1]} -offset 104 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FAFC_FMULTI[0]} -offset 104.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[15]} -offset 105.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[14]} -offset 105.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[13]} -offset 106.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[12]} -offset 107 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[11]} -offset 107.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[10]} -offset 108.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[9]} -offset 108.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[8]} -offset 109.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[7]} -offset 110 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[6]} -offset 110.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[5]} -offset 111.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[4]} -offset 111.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[3]} -offset 112.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[2]} -offset 113 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[1]} -offset 113.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_TDCRESNORM[0]} -offset 114.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_AUXMMD_SEL} -offset 114.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN[7]} -offset 115.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN[6]} -offset 116 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN[5]} -offset 116.6 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN[4]} -offset 117.2 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN[3]} -offset 117.8 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN[2]} -offset 118.4 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN[1]} -offset 119 -layers {M4} -width 0.1 -depth 0 -side 4
set_pin_physical_constraints -pin_name {SPI_FCW_MGN[0]} -offset 119.6 -layers {M4} -width 0.1 -depth 0 -side 4
