set_pin_physical_constraints -pin_name {SPI_AFC_EN} -offset 6 -layers {M4} -width 0.08 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SPI_NARST} -offset 6.6 -layers {M4} -width 0.08 -depth 0 -side 2


set_pin_physical_constraints -pin_name {AFC_CTRL} -offset 6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {FREQLOCK} -offset 6.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWP[8]} -offset 7.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWP[7]} -offset 7.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWP[6]} -offset 8.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWP[5]} -offset 9 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWP[4]} -offset 9.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWP[3]} -offset 10.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWP[2]} -offset 10.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWP[1]} -offset 11.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWP[0]} -offset 12 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWN[8]} -offset 12.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWN[7]} -offset 13.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWN[6]} -offset 13.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWN[5]} -offset 14.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWN[4]} -offset 15 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWN[3]} -offset 15.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWN[2]} -offset 16.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWN[1]} -offset 16.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {AFC_OTWN[0]} -offset 17.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[8]} -offset 18 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[7]} -offset 18.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[6]} -offset 19.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[5]} -offset 19.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[4]} -offset 20.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[3]} -offset 21 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[2]} -offset 21.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[1]} -offset 22.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_MMD_P_O[0]} -offset 22.8 -layers {M3} -width 0.08 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[6]} -offset 25.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[5]} -offset 25.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[4]} -offset 26.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[3]} -offset 27 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[2]} -offset 27.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[1]} -offset 28.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_MULTI_O[0]} -offset 28.8 -layers {M3} -width 0.08 -depth 0 -side 3

set_pin_physical_constraints -pin_name {SPI_FCW_O[16]} -offset 40.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[15]} -offset 40.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[14]} -offset 41.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[13]} -offset 42 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[12]} -offset 42.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[11]} -offset 43.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[10]} -offset 43.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[9]} -offset 44.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[8]} -offset 45 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[7]} -offset 45.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[6]} -offset 46.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[5]} -offset 46.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[4]} -offset 47.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[3]} -offset 48 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[2]} -offset 48.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[1]} -offset 49.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_FCW_O[0]} -offset 49.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {REF} -offset 50.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {CKVD} -offset 51 -layers {M3} -width 0.08 -depth 0 -side 3
