
set_pin_physical_constraints -pin_name {CKVD} -offset 6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {PHE_SIG} -offset 6.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {PHE_SIG2} -offset 7.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {LO_STATE[1]} -offset 7.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {LO_STATE[0]} -offset 8.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {VDACCTRL_OUTP[1]} -offset 9 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {VDACCTRL_OUTP[0]} -offset 9.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {VDACCTRL_OUTN[1]} -offset 10.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {VDACCTRL_OUTN[0]} -offset 10.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[11]} -offset 11.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[10]} -offset 12 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[9]} -offset 12.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[8]} -offset 13.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[7]} -offset 13.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[6]} -offset 14.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[5]} -offset 15 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[4]} -offset 15.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[3]} -offset 16.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[2]} -offset 16.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[1]} -offset 17.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DCW_DELAY[0]} -offset 18 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[8]} -offset 18.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[7]} -offset 19.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[6]} -offset 19.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[5]} -offset 20.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[4]} -offset 21 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[3]} -offset 21.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[2]} -offset 22.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[1]} -offset 22.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_P[0]} -offset 23.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_S[2]} -offset 24 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_S[1]} -offset 24.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_S[0]} -offset 25.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[8]} -offset 25.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[7]} -offset 26.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[6]} -offset 27 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[5]} -offset 27.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[4]} -offset 28.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[3]} -offset 28.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[2]} -offset 29.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[1]} -offset 30 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP[0]} -offset 30.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[8]} -offset 31.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[7]} -offset 31.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[6]} -offset 32.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[5]} -offset 33 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[4]} -offset 33.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[3]} -offset 34.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[2]} -offset 34.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[1]} -offset 35.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS[0]} -offset 36 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[8]} -offset 36.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[7]} -offset 37.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[6]} -offset 37.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[5]} -offset 38.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[4]} -offset 39 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[3]} -offset 39.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[2]} -offset 40.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[1]} -offset 40.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_N[0]} -offset 41.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[8]} -offset 42 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[7]} -offset 42.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[6]} -offset 43.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[5]} -offset 43.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[4]} -offset 44.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[3]} -offset 45 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[2]} -offset 45.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[1]} -offset 46.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CS_N[0]} -offset 46.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL_O[2]} -offset 47.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL_O[1]} -offset 48 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {SPI_OTWSEL_O[0]} -offset 48.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_PHESIG_GEN_EN} -offset 49.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_DTC_GAINCAL_EN} -offset 49.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_DN_EN} -offset 50.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_DTC_EN} -offset 51 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_MMD_EN} -offset 51.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_DSM_EN} -offset 52.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_PDS_EN} -offset 52.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_PRECHARGE_EN} -offset 53.4 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_PFD_EN} -offset 54 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CP_EN} -offset 54.6 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_SPD_EN} -offset 55.2 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_SNPCNTTDC_EN} -offset 55.8 -layers {M3} -width 0.08 -depth 0 -side 3
set_pin_physical_constraints -pin_name {O_CNTPREDIV_EN} -offset 56.4 -layers {M3} -width 0.08 -depth 0 -side 3
